### ISSUE TITLE
URL parameter recognition issues

### ISSUE THREAD

**Issue by Hun-Su** [iamshaunjp/flutter-beginners-tutorial#35]
Hi, Shaun.

I have started a new project on building an app on iOS and Android using Flutter recently. Since I was new to Flutter I was looking for some videos where I can learn about it and I found your videos. I really love them and I find them very helpful, but I just have one concern regarding getting information from the web.

In building the world time app, I was trying to get the API from the web and my Android Studio seems like it cannot recognize the JSON URL as a URL, but as a String. I have been looking for solutions on the web, but since Flutter is relatively new, I couldn't solve my issue. I would be really grateful If you could help. The bottom is the screenshot of it.

Thank you in advance.

![Flutter issue](https://user-images.githubusercontent.com/50570659/110314760-9f648680-804b-11eb-8fbc-69c1db6ca0ba.PNG)

**Comment by ankit3466** [comment]
I am also facing the same issue. Did you get anything?

**Comment by Hun-Su** [comment]
Not yet. I am still waiting for some help.

**Comment by rafaelwillen** [comment]
It's probably the http package has updated since then. 
To use it now you do this:

`get(new Uri.https("worldtimeapi.org", "/api/timezone/Europe/London"));`

The first parameter in the Uri object is the base URL of the end point, and the second is the rest of the URL. Take note that there are Uri.http and Uri.https, but with http it didn't worked.

**Comment by Hun-Su** [comment]
@rafaelwillen Problem solved! Thank you :)
